import { defineTool, type ToolRegistryEntry } from "../toolDefinition.js";

export const reminderToolContracts = [
  defineTool({
    name: "setReminder",
    examples: ["@ai remind me tomorrow at 9 to call Mom", "@ai every morning summarize yesterday's Discord activity", "@ai pause this", "@ai move the next one to Friday at 10"],
    description: "Create or manage the requester's schedule. delivery_mode notification sends literal text; agent runs fresh read-only work at delivery. Create needs reminder and future scheduled_for. Omit reminder_id only in a direct reply to the latest delivery. Recurring time edits need update_scope; series edits need the full recurrence and first delivery. remove_recurrence makes it one-shot.",
    mutates: true,
    group: "core",
    category: "memory",
    toolClass: "memory",
    outputContract: ["resolved schedule ID", "notification or read-only agent mode", "requester-local schedule and recurrence", "durable mutation", "explicit series ambiguity"],
    permissionRequirements: ["explicit_current_turn_request", "immutable_current_requester", "current_guild_scope", "current_channel_delivery", "tool_audit_log"],
    argumentExamples: [
      { action: "create", reminder: "call Mom", delivery_mode: "notification", scheduled_for: "2026-08-06T09:00:00-04:00", timezone: "America/New_York" },
      { action: "create", reminder: "summarize yesterday's Discord activity", delivery_mode: "agent", scheduled_for: "2026-08-06T09:00:00-04:00", timezone: "America/New_York" },
      { action: "pause" },
      { action: "update", scheduled_for: "2026-08-07T10:00:00-04:00", update_scope: "next_occurrence" },
    ],
    parameters: {
      type: "object",
      properties: {
        action: { type: "string", enum: ["create", "cancel", "pause", "resume", "update"] },
        reminder_id: { type: "string", minLength: 3, maxLength: 80 },
        reminder: { type: "string", minLength: 1, maxLength: 1500 },
        delivery_mode: { type: "string", enum: ["notification", "agent"] },
        scheduled_for: { type: "string", minLength: 20, maxLength: 40 },
        timezone: { type: "string", minLength: 1, maxLength: 100 },
        recurrence: {
          type: "object",
          properties: {
            frequency: { type: "string", enum: ["daily", "weekly", "monthly"] },
            interval: { type: "integer", minimum: 1, maximum: 366 },
            local_time: { type: "string", pattern: "^([01]\\d|2[0-3]):[0-5]\\d$" },
            weekdays: { type: "array", minItems: 1, maxItems: 7, uniqueItems: true, items: { type: "string", enum: ["sunday", "monday", "tuesday", "wednesday", "thursday", "friday", "saturday"] } },
            day_of_month: { type: "integer", minimum: 1, maximum: 31 },
          },
          required: ["frequency", "local_time"],
          additionalProperties: false,
        },
        remove_recurrence: { type: "boolean" },
        update_scope: { type: "string", enum: ["series", "next_occurrence"] },
      },
      required: ["action"],
      additionalProperties: false,
    },
  }),
  defineTool({
    name: "listMyReminders",
    examples: ["@ai what reminders do I have?", "@ai list my scheduled briefings", "@ai what happened with my morning summary?"],
    description: "List the requester's active and recent schedules in this server, including next time, last-run outcome/result, failure health, and automatic pauses.",
    mutates: false,
    group: "core",
    category: "memory",
    toolClass: "memory",
    outputContract: ["active and recent schedule IDs", "notification or agent mode", "request text", "next and last requester-local times", "last outcome and visible result link", "failure and pause health", "result count"],
    permissionRequirements: ["immutable_current_requester", "current_guild_scope", "tool_audit_log"],
    parameters: { type: "object", properties: {}, additionalProperties: false },
  }),
] satisfies ToolRegistryEntry[];
